module.exports = [
  {
    name: 'Madison Square Garden',
    type: 'Arena',
    year: '',
    capacity: 18000,
    cost: null,
    nicknames: [],
    stillExists: true,
    pSport: 'Basketball',
    pTeam: 'New York Knicks',
    sSports: ['Hockey'],
    sTeams: ['New York Rangers', 'St. John\'s Red Storm'],
    city: 'New York City',
    state: 'New York',
    country: 'USA',
    outsideImg: '',
    insideImg: '',
    highlightURL: '',
    mapsURL: '',
    links: {
      website: 'https://www.msg.com/madison-square-garden',
      twitter: '',
      fb: '',
      ig: ''
    }
  },
  {
    name: 'Shea Stadium',
    type: 'Stadium',
    year: '',
    capacity: 30000,
    cost: null,
    nicknames: [],
    stillExists: false,
    pSport: 'Baseball',
    pTeam: 'New York Mets',
    sSports: [],
    sTeams: [],
    city: 'New York City',
    state: 'New York',
    country: 'USA',
    outsideImg: '',
    insideImg: '',
    highlightURL: '',
    mapsURL: '',
    links: {
      website: '',
      twitter: '',
      fb: '',
      ig: ''
    }
  },
  {
    name: 'Los Angeles Coliseum',
    type: 'Stadium',
    year: '',
    capacity: 100000,
    cost: null,
    nicknames: [],
    stillExists: true,
    pSport: 'Football',
    pTeam: 'USC Trojans',
    sSports: ['Olympics'],
    sTeams: [],
    city: 'Los Angeles',
    state: 'California',
    country: 'USA',
    outsideImg: '',
    insideImg: '',
    highlightURL: '',
    mapsURL: '',
    links: {
      website: '',
      twitter: '',
      fb: '',
      ig: ''
    }
  },
]